### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by Amireux52** [IamMRM/Convolutional-Neural-Networks-for-Direct-Text-Deblurring#2]
D:\anaconna32021.11anzhuangweizhi\envs\CNNL15\python.exe E:/CNNL15debug/train.py
0
0
Traceback (most recent call last):
  File "E:/CNNL15debug/train.py", line 185, in <module>
    inputs, masks = next(iter(DataLoader(train_set, batch_size=batch_size, shuffle=False, num_workers=0)))
  File "D:\anaconna32021.11anzhuangweizhi\envs\CNNL15\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\anaconna32021.11anzhuangweizhi\envs\CNNL15\lib\site-packages\torch\utils\data\dataloader.py", line 474, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "D:\anaconna32021.11anzhuangweizhi\envs\CNNL15\lib\site-packages\torch\utils\data\dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration

Process finished with exit code 1
Hello, may I ask how to solve this problem

**Comment by IamMRM** [comment]
You have a problem with the data loader. You need to check the directory where you have the data
